# Generated by Django 4.2.27 on 2026-01-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CowProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(help_text='Unique policy/registration ID', max_length=100, unique=True)),
                ('cow_name', models.CharField(max_length=100)),
                ('cow_age', models.IntegerField(blank=True, help_text='Age of the cow in months or years', null=True)),
                ('cow_breed', models.CharField(blank=True, help_text='Breed of the cow', max_length=100)),
                ('owner_name', models.CharField(blank=True, help_text='Name of the cow owner', max_length=200)),
                ('cow_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cow_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('policy_id', 'cow_name')},
            },
        ),
    ]
