# Generated by Django 4.2.27 on 2026-01-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('num_images', models.IntegerField(blank=True, null=True)),
                ('epochs', models.IntegerField(blank=True, null=True)),
                ('checkpoint_path', models.CharField(blank=True, max_length=500)),
                ('cow_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_status', to='api.cowprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
