# Generated by Django 4.2.27 on 2026-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowprofile',
            name='policy_id',
            field=models.CharField(help_text='Policy/registration ID (unique together with cow_name)', max_length=100),
        ),
    ]
